version: '3.4'
services:
  linuxgsm-pw:
    image: gameservermanagers/gameserver:pw
    container_name: pwserver
    restart: unless-stopped
    volumes:
      - linuxgsm-pw:/data
    #network_mode: host
    stop_grace_period: 30s
    ports:
      - "8211:8211/udp"
      - "27015:27015/udp"
    expose:
      - "25575/tcp"
    secrets:
      - server_password

secrets:
  server_password:
    file: ./server_password.txt

volumes:
  linuxgsm-pw:
